### ISSUE TITLE
Verify the proper sector is recorded by 'disk_wrapper'

### ISSUE THREAD

**Issue by ashmrtn** [utsaslab/crashmonkey#26]
Comments in the kernel indicate that the `bi_sector` that our current logging may not be relative to the partition we're monitoring, but relative to the entire block device ([offending comment](http://elixir.free-electrons.com/linux/latest/source/block/blk-core.c#L1913)). We need to determine if the sector being logged is the sector relative to the partition of the device we are monitoring or the disk itself (ex. relative to `/dev/sda1` or `/dev/sda`).

An easy way to check this is to log some operations with CrashMonkey and then try to replay those operations onto a device with a different number of partitions and/or with partitions of different sizes than the device logging was originally done on.

**Comment by gk159yo** [comment]
This took a lot longer to resolve than expected due to us trying to modify the source code and a bunch of other misunderstandings and problems.

Anyways, we went with Ashley's suggested approach to solve this issue.
This is the `bio` data (bolded) for a ramdisk with 1 partition, with the wrapper recording data for the first partition (when we copied over a very small file):
` 
 [ 1075.XXXXX] hwm: bio rw of size 1024 headed for **0x109800 (sector 0x84c)** has flags:
  ...
 [ 1075.XXXXX] hwm: bio rw of size 1024 headed for **0x109c00 (sector 0x84e)** has flags:
`
This is the `bio` data (bolded) for a ramdisk with 2 partitions, with the wrapper recording data for the second partition (when we copied over the same file as before):
`
 [17361.XXXXX] hwm: bio rw of size 1024 headed for **0x509800 (sector 0x284c)** has flags:
 [17361.XXXXX] hwm: bio rw of size 1024 headed for **0x505800 (sector 0x282c)** has flags:
`
We can see that the sector numbers are different. 
It thus seems safe to assume that the `bi_sector` is relative to the first sector in the device and not the first sector in the partition.

**Comment by ashmrtn** [comment]
The work these three have done has also shown that there is two possibilities when it comes to wrapping a device with multiple partitions:
1. a user could use `disk_wrapper` to wrap an entire block device with multiple partitions
1. a user could use `disk_wrapper` to wrap a single partition on a block device with multiple partitions

The current `disk_wrapper` seems to have issues with point 2 above (something about trying to access sectors past the end of the device), but Subrat et al. were able to do part 1 above. Since part 1 above creates multiple block devices in `disk_wrapper` (one per partition) it make sense that the blocks would be relative to the start of the block device. If we wish to investigate part 2 above, we will need to fix `disk_wrapper` and then try giving it only a single partition for the `target_device_path`. I suspect that in the case of point 2 above we will see the block address from the start of the partition as `disk_wrapper` will only present 1 block device to the system.
